# Generated by Django 5.0.6 on 2024-06-17 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('barcode', models.CharField(max_length=50, verbose_name='Barcode')),
                ('consumable', models.BooleanField(default=False, verbose_name='Consumable')),
                ('units', models.CharField(choices=[('units', 'Units'), ('meters', 'Meters'), ('liters', 'Liters')], max_length=20, verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Request',
                'verbose_name_plural': 'Material Requests',
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('amount_returned', models.IntegerField(default=0, verbose_name='Amount returned')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.item')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.materialrequest')),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Requirement',
                'verbose_name_plural': 'Material Requirements',
            },
        ),
        migrations.CreateModel(
            name='ItemRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.item')),
                ('material_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.materialrequirement')),
            ],
            options={
                'verbose_name': 'Item Requirement',
                'verbose_name_plural': 'Item Requirements',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
