# Generated by Django 5.0.6 on 2024-07-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='unit_price',
            field=models.FloatField(verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(verbose_name='Unit Price'),
        ),
    ]
