# Generated by Django 5.0.6 on 2024-06-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'item')},
        ),
    ]
