# Generated by Django 5.0.6 on 2024-07-23 01:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_historicalitem_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitemrequirement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitemrequirement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalitemrequirement',
            name='material_requirement',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='material_request',
        ),
        migrations.RemoveField(
            model_name='itemrequirement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemrequirement',
            name='material_requirement',
        ),
        migrations.CreateModel(
            name='HistoricalStockRequest',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('modified_at', models.DateField(blank=True, editable=False, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('amount_returned', models.IntegerField(default=0, verbose_name='Amount returned')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.materialrequest')),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.stock')),
            ],
            options={
                'verbose_name': 'historical Item Request',
                'verbose_name_plural': 'historical Item Requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockRequirement',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('modified_at', models.DateField(blank=True, editable=False, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_requirement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.materialrequirement')),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.stock')),
            ],
            options={
                'verbose_name': 'historical Item Requirement',
                'verbose_name_plural': 'historical Item Requirements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('amount_returned', models.IntegerField(default=0, verbose_name='Amount returned')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.materialrequest')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stock')),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
            },
        ),
        migrations.CreateModel(
            name='StockRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Deletion date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('material_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.materialrequirement')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stock')),
            ],
            options={
                'verbose_name': 'Item Requirement',
                'verbose_name_plural': 'Item Requirements',
            },
        ),
        migrations.DeleteModel(
            name='HistoricalItemRequest',
        ),
        migrations.DeleteModel(
            name='HistoricalItemRequirement',
        ),
        migrations.DeleteModel(
            name='ItemRequest',
        ),
        migrations.DeleteModel(
            name='ItemRequirement',
        ),
    ]
