# Generated by Django 5.0.6 on 2024-07-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='granted',
            field=models.BooleanField(default=False, verbose_name='Granted'),
        ),
    ]
