# Generated by Django 5.0.6 on 2024-07-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_materialrequest_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode'),
        ),
    ]
